//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_05.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class adminProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public adminProduct()
        {
            this.addToCarts = new HashSet<addToCart>();
        }
    
        public int productid { get; set; }
        public string productname { get; set; }
        public double productprice { get; set; }
        public string productpicture { get; set; }
        public string productcategory { get; set; }
        public string productqty { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<addToCart> addToCarts { get; set; }
    }
}
