//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_05.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class deliveryDetail
    {
        public int deliveryid { get; set; }
        public string deliverydate { get; set; }
        public string recipientname { get; set; }
        public string recipientsurname { get; set; }
        public string phonenumber { get; set; }
        public string streetname { get; set; }
        public string areaname { get; set; }
        public string city { get; set; }
        public string province { get; set; }
        public string additionalinformation { get; set; }
        public Nullable<int> customerid { get; set; }
    
        public virtual customer customer { get; set; }
    }
}
