//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_05.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class driver
    {
        public int driverId { get; set; }
        public string driveremail { get; set; }
        public string password { get; set; }
        public string surname { get; set; }
        public int contact { get; set; }
        public string firstname { get; set; }
    }
}
