//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_05.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier
    {
        public int Id { get; set; }
        public string supplieremail { get; set; }
        public string password { get; set; }
        public string surname { get; set; }
        public string firstname { get; set; }
        public int contact { get; set; }
        public Nullable<int> oderid { get; set; }
        public Nullable<int> custumerid { get; set; }
    }
}
